(function(m,k,h,f){function g(a){var n,A,c,b,d,e;n=w[a];if(!n)throw Error('Requiring unknown module "'+a+'"');if(n.hasOwnProperty("exports"))return n.exports;n.exports=a={};A=n.deps;e=A.length;d=-1;for(b=[];++d<e;)c=A[d],b.push("module"===c?n:"exports"===c?a:g(c));if((A=n.factory.apply(null,b))!==f)n.exports=a=A;return a}function b(a,n,c){n=["global","require","module","exports"].concat(n);w[a]={factory:c,deps:n}}function e(a,n,c){var b=Array.prototype.slice;e=function(a,n,c){var A=b.call(arguments,
1);return b.apply(a,A)};return e.apply(this,e(arguments,0))}function a(a,n){n=n||h;return n.getElementById(a)}function d(a){for(var a=a||{},n=arguments,c=n.length,b=0,d,e;++b<c;)for(e in d=n[b],d)d.hasOwnProperty(e)&&(a[e]=d[e]);return a}function c(a,n,b){var e;this instanceof c?(this.constructor=a,d(this,b)):(e=c.prototype,c.prototype=n.prototype,a.prototype=new c(a,n,b),c.prototype=e)}function i(){function a(){for(var d=-1,e;++d<c;)e=n[d],e[0].apply(e[1],e[2]),delete n[d];n=[];c=0;b=null}var n=
[],b=null,c=0;i=function(d,j,f){if(!d)return i;n.push([d,j||this,e(arguments,2)]);c++;null===b&&(b=setTimeout(a,0));return b};return i.apply(this,e(arguments,0))}function l(a){var b,c=h.getElementsByTagName("head");b=c.length&&c[0]||h.body;l=function(a){b.appendChild(a)};return l(a)}function q(a,b){var c=o(a)?[]:{};"function"!=typeof b&&(b=b===f?function(a,b){return!!b}:function(a,c){return c==b});p(a,function(a,d){b(a,d)&&(c[a]=d)});return c}function r(a,b,c){var d,e;d=h.createElement(a);e=d.style;
b&&p(b,function(a,b){d[a]=b});e&&c&&p(c,function(a,b){e[a]=b});return d}function p(a,b){y(a,function(a,c){b(a,c);return!1})}function y(a,b){var c;c=a.length;return(c===f||x(a)?function(a,b){for(var c in a)if(a.hasOwnProperty(c)&&b(c,a[c]))return!0;return!1}:function(a,b){var d;for(d=0;d<c;d++)if(b(d,a[d]))return!0;return!1})(a,b)}function t(a){for(var b="Boolean,Number,String,Function,Array,Date,RegExp,Object".split(","),c=b.length,d=Object.prototype.toString,e={},i;c--;)i=b[c],e["[object "+i+"]"]=
i.toLowerCase();t=function(a){return null==a?""+a:e[d.call(a)]||"object"};return t(a)}function x(a){return"function"===t(a)}function o(a){function b(a){return"array"===t(a)}o=Array.isArray||b;return o(a)}function x(a){return"[object Function]"==Object.prototype.toString.call(a)}function j(a,b){return D(a,b,e(arguments,2))}function D(a,b,c){E.push([a,b,c]);if(!z){for(z=!0;a=E.length;){for(b=0;b<a;b++)c=E[b],c[0].apply(c[1],c[2]);E.splice(0,a)}z=!1}}var w={};w.global={exports:m};w.require={exports:g};
var B={addHandler:function(a,b,c){a.addEventListener?a.addEventListener(b,c,!1):a.attachEvent?a.attachEvent("on"+b,c):a["on"+b]=c},getEvent:function(a){return a?a:k.event},getTarget:function(a){return a.target||a.srcElement},preventDefault:function(a){a.preventDefault?a.preventDefault():a.returnValue=!1},stopPropagation:function(a){a.stopPropagation?a.stopPropagation():a.cancelBubble=!0},removeHandler:function(a,b,c){a.removeEventListener?a.removeEventListener(b,c,!1):a.detachEvent?a.detachEvent("on"+
b,c):a["on"+b]=null}},E=[],z=!1;b("Arbiter",["global"],function(a,b){function c(a){this._listenerMap={};this._setup(a||[])}function i(a,b){var c=a[0],d=a[1],b=a[2].concat(b);try{return c.apply(d,b)}catch(e){setTimeout(function(){throw e;},0)}}a=b("global");d(c.prototype,{_setup:function(a){for(var b=a.length,c=this._listenerMap;b--;)c[a[b]]={args:null,cbs:[]}},on:function(b,c,d){var i=this._listenerMap[b],j,s;if(!i)return!1;d=d||a;j=e(arguments,3);(s=i.args)?D(c,d,j.concat(s)):i.cbs.push([c,d,j]);
return!0},done:function(a,b){var c=this._listenerMap[a],d,i,s;if(!c)return!0;i=c.cbs;s=i.length;b=e(arguments,1);c.args=b;d=this.emit.apply(this,arguments);c.cbs=i.slice(s);return d},emit:function(a,b){var c=this._listenerMap[a],d,j,s;if(!c)throw Error(a+" has not listened");b=e(arguments,1);c=c.cbs;d=c.length;j=-1;for(s=!0;++j<d;)s=!1!==i(c[j],b)&&s;return!!s},undo:function(a){a=this._listenerMap[a];if(!a)return!1;a.args=null}});return c});b("Resource",["Arbiter","CSSLoader","JSLoader"],function(a,
b){function e(a,b){if(this instanceof e)h.call(this,u),this.id=a,this.deps=b,this.loaded=!1,this.state=v;else return i(a)}function i(a){var b,c;if(!(b=o[a]))throw Error('resource "'+a+'" unknow.');if(!(c=b._handler))c=b._handler=new e(a,b.deps||[]),b._loaded&&(c.loaded=!0);return c}function g(a,b){C[a]=b}function l(a,b){var c;if(b!==f)c=o[a]||{},d(c,b),o[a]=c;else for(a in b=a,b)l(a,b[a])}var h=b("Arbiter"),o={},C={},s={},u=["load","resolve"],v=1;c(e,h,{load:function(){function a(){--d||(f=!0,v&&
this.done("resolve"))}function b(){v=!0;this.done("load");f&&this.done("resolve")}var c,d,u,s,i,v,f;if(2<=this.state)return!1;this.state=2;v=this.loaded;f=!0;c=this.deps;u=d=c.length;if(0<u){f=!1;for(s=-1;++s<u;)i=e(c[s]),i.on("resolve",a,this),i.load()}j(function(){var a;if(v)j(b,this);else{a=this.id;var c,d,e;c=o[a];d=c.type;if(!(e=C[d]))throw Error('unknow type "'+d+'"');a=new e(a,c);a.on("load",b,this);a.load()}},this)}});d(e,{setResourceMap:l,setModuleMap:function(a){d(s,a)},setResourceLoaded:function(a){var b;
for(b=a.length;b--;)l(a[b],{_loaded:!0})},moudelToResource:function(a){var b=s[a];if(!b)throw Error('module "'+a+'" unknow.');return i(b)}});g("css",b("CSSLoader"));g("js",b("JSLoader"));return e});b("Pagelet",["Arbiter","Resource"],function(b,e){function j(a){if(this instanceof j)f.call(this,l),this.id=a,this.root=null===a,this.state=o;else{var b;if(null===a)return new j(a);b=h[a];b||(b=new j(a),h[a]=b);return b}}var f=e("Arbiter"),g=e("Resource"),l="arrive,beforeload,cssresolved,jsresolved,beforedisplay,display,load,afterload,resolved,beforeunload,unload,afterunload".split(","),
o=0,h={},C={};c(j,f,{arrive:function(a){d(this,{html:a.html||"",css:a.css||[],js:a.js||[],parent:a.parent||null,children:a.children||[],state:1});this.afterload=!1;this.done("arrive");this.emit("beforeload")?this.load():(this.afterload=!0,this.done("afterload"))},load:function(){function a(){j(this.parent).on("display",b,this)}function b(){this.emit("beforedisplay")&&this.display()}if(2<=this.state)return!1;this.state=2;this.on("cssresolved",this.parent?a:b,this);this._resolve(this.css,"cssresolved");
this._resolve(this.js,"jsresolved")},setState:function(){if(3>this.state)return!1;this.state=4;var a,b,c,d;a=this.children;b=a.length;c=-1;if(b)for(;++c<b;)d=a[c],d=j(d),d.setState()},doUnload:function(){function a(){--b||this.emit("beforeunload")&&this.unload()}var b,c,d,e,i;c=this.children;d=b=c.length;e=-1;if(d)for(;++e<d;)i=c[e],i=j(i),i.on("unload",a,this),i.doUnload();else this.emit("beforeunload")&&this.unload()},remove:function(){if(4==this.state)return!1;this.setState();this.on("unload",
this.destroy,this);this.doUnload()},unload:function(){this.done("unload")},destroy:function(){var a,b,c,d;a=this.children;b=a.length;c=-1;if(b)for(;++c<b;)d=a[c],d=j(d),d.destroy();delete h[this.id];this.state=o;i(this.done,this,"afterunload")},isUnloading:function(){return 4==this.state},_resolve:function(a,b){function c(){--d||this.done(b)}var d,e,i,j;e=d=a.length;i=-1;if(e)for(;++i<e;)j=g(a[i]),j.on("resolve",c,this),j.load();else this.done(b)},display:function(){if(3<=this.state)return!1;this.state=
3;this.root||(a(this.id).innerHTML=this.html);this.done("display");this.on("jsresolved",function(){this.done("load");this.afterload||this.done("afterload")},this)},get:function(a,b){return C[a]||b},set:function(a,b){C[a]=b}});d(j,{hasPagelet:function(a){return!!h[a]}});return j});b("BigPipe",["Resource","Pagelet","Emulator","Arbiter","Requestor"],function(a,b){function d(){j.call(this);this.hooks={}}var e=b("Resource");b("Pagelet");var i=b("Emulator"),j=b("Arbiter"),f=b("Requestor"),g=!1;c(d,j,{init:function(a){if(g)throw Error("BigPipe has been initialized.");
g=!0;this.emulator=i();this.emulator.listen();this.emulator.on("request",this.request,this);this.requestor=new f(a)},onPageletArrive:function(a){var b=a.callback,c,d,i,j,f,g,l=this.hooks;if(b){c=a.hook||{};for(var h in b){d=b[h];i=-1;j=d.length;for(f=c[h]||[];++i<j;)g=d[i],f.push(l[g]),delete l[g];c[h]=f}a.hook=c}e.setResourceMap(a.map||{});e.setModuleMap(a.mods||{});this.requestor.arrive(a)},request:function(a,b){this.requestor.request(a,b)},sessionStart:function(a){this.requestor.start(a)},sessionEnd:function(a){this.requestor.end(a)},
loadModule:function(a,b){var c=e.moudelToResource(a);c.on("resolve",b);c.load()},loadedResource:function(a){e.setResourceLoaded(a)},log:function(){}});return d});b("CSSLoader",["Arbiter"],function(a,b){function d(a,b){u.call(this,v);this.id=a;this.url=b.src;this.state=D}function e(a){r||(r=h.createElement("meta"),l(r));z=a||z;r.className=z.join(" ")}function j(a){return!a?!1:(a=k.getComputedStyle?getComputedStyle(a,null):a.currentStyle)&&1<parseInt(a.height,10)}function f(){var a,b,c,d,i,g,l,u,h,
o,v,n;b=2<z.length?j(r):!0;c=0;d=[];i=!1;g=+new Date;for(a in p){l=p[a];u=l[0];h=!1;b&&j(u)&&(h=!0);for(v=1,o=l.length;v<o;v++)n=l[v],h?n[1].call(n[2],!0):n[0]<g&&(n[1].call(n[2],!1),l.splice(v,1),v--,o--);h||1==o?(u.parentNode.removeChild(u),delete p[a],i=!0):(d.push("css_"+a),c++)}c?(i&&e(d),setTimeout(f,20)):(z=[],r&&(r.parentNode.removeChild(r),r=null),y=!1)}function g(a,b,c,d){var j,u;if(!(j=p[a]))u="css_"+a,j=h.createElement("meta"),j.className=u,l(j),j=[j],p[a]=j,z.push(u),e();b=+new Date+
b;j.push([b,c,d]);y||(y=!0,i(f))}function o(a){this.state=a?m:B;this.done("load",a)}function w(){var a=this.id,b=this.url,c=h.createElement("link");c.rel="stylesheet";c.type="text/css";c.href=b;l(c);g(a,q,o,this)}function s(){for(var a=this.id,b=this.url,c=t.length,d=c,e;d--;)if(31>t[d].length){e=x[d];break}0>d&&(e=h.createStyleSheet(),x.push(e),t.push([]),d=c);e.addImport(b);t[d].push(b);g(a,q,o,this)}var u=b("Arbiter"),v=["load"],D=1,m=3,B=4,q=5E3,y=!1,t=[],x=[],p={},z=[],r=null;c(d,u,{load:function(){2>
this.state&&(this.state=2,this._load())},_load:h.createStyleSheet?s:w});return d});b("JSLoader",["Arbiter"],function(a,b){function d(a,b){e.call(this,j);this.id=a;this.url=b.src;this.state=g}var e=b("Arbiter"),j=["load"],g=1,o=3,w=4;c(d,e,{load:function(){function a(j){if(!(b.state>=o)){b.state=j?o:w;b.done("load");k[c]=d;if(d===f)try{delete k[c]}catch(g){}i(function(){e.onerror=null;e.parentNode&&e.parentNode.removeChild(e);e=null})}}var b=this,c,d;if(!(2<=this.state)){this.state=2;var e=h.createElement("script");
e.src=this.url;e.async=!0;e.onerror=function(){a(!1)};c="js_"+this.id;d=k[c];k[c]=a;l(e)}}});return d});b("Emulator",["Arbiter","Pagelet"],function(a,b){function d(a){var b=!1;if(a&&(a=(""+a).replace(/(^\s*)|(\s*$)/g,"")))b=q(a.split(" "),function(a,b){return!!(""+b).replace(/(^\s*)|(\s*$)/g,"")});return b}function e(a){var b,c;for(b="A";a&&a.nodeName!=b;)a=a.parentNode;if(!a)return!1;if(!this.emit("beforetrigger",a))return!0;b=a.href;if(!b)return!1;b=b==f||0==b.indexOf(f+"/")?b.substring(l)||"/":
!1;if(!b)return!1;(a=a.rel)&&(c=d(a));if(!c)return!1;this.emit("request",b,c);return!0}function j(){if(this instanceof j)i.call(this,o);else return g||(g=new j),g}var i=b("Arbiter");b("Pagelet");var g,f,l,o=["beforetrigger","request"];f=[location.protocol,"//",location.host].join("");l=f.length;c(j,i,{listen:function(){var a=this;B.addHandler(h.documentElement,"click",function(b){var c,b=B.getEvent(b);c=B.getTarget(b);e.call(a,c)&&B.preventDefault(b)})}});return j});b("Requestor",["Arbiter","Pagelet",
"Controller"],function(a,b){function e(a){j.call(this,f);d(this,{ajaxKey:a.ajaxKey,separator:a.separator,sessionKey:a.sessionKey});l||this.init()}var j=b("Arbiter");b("Pagelet");var i=b("Controller"),f=["arrive","allarrived"],g={},l=!1,o=!1,w=0;c(e,j,{init:function(){l=!0;this.sessionState=this.state=0;this.controller=new i;this.controller.on("arrived",this._onItemArrived,this);this.on("allarrived",this._onSessionEnd,this);this.refCount=0},start:function(a){this.sessionID=a;switch(this.sessionState){case 1:case 2:case 3:this.sessionState=
2;break;case 0:this.sessionState=1}},end:function(){this.sessionState=3;0==this.refCount&&this._onSessionEnd()},arrive:function(a){var b=this.sessionID,c=this.sessionState;g[b-1]&&(g[b-1]=null);2==c||3==c?(g[b]=g[b]||[],g[b].push(a)):(++this.refCount,this.controller.handdleArrive(a))},request:function(a,b){w++;this._ajaxRequest([a,/.*\?.*/.test(a)?"&":"?",this.ajaxKey,b?"="+b.join(this.separator):"","&",this.sessionKey,"=",w].join(""))},_onSessionEnd:function(){this.sessionState=0;var a=g[this.sessionID],
b=this;a&&p(a,function(a,c){b.refCount++;b.controller.handdleArrive(c)})},_onItemArrived:function(){!--this.refCount&&3==this.sessionState&&this.emit("allarrived")},_ajaxRequest:function(a){switch(this.state){case 1:var b=this._ajaxIframe;b&&b.parentNode&&b.parentNode.removeChild(b);this._initAjaxIframe(a);break;case 0:this._initAjaxIframe(a),this.state=1}},_initAjaxIframe:function(a){var b=this;this._ajaxIframe=r("iframe",{src:a},{display:"none"});h.body.appendChild(this._ajaxIframe);clearTimeout(o);
B.addHandler(this._ajaxIframe,"load",function(){1==b.state&&(o=setTimeout(function(){var a=b._ajaxIframe;a&&a.parentNode&&a.parentNode.removeChild(a);b.state=0},100))})}});return e});b("Controller",["Arbiter","Pagelet","Resource"],function(b,d){function e(){i.call(this,f)}function j(b,c){var d=a(b,c),e;if(!(e=d.firstChild)||8!==e.nodeType)return null;e=e.nodeValue;d.parentNode.removeChild(d);e=e.slice(1,-1);return e.replace(/--\\>/g,"--\>")}var i=d("Arbiter"),g=d("Pagelet");d("Resource");var f=["arrived"];
c(e,i,{handdleArrive:function(a){var b,c;c=a.id;g.hasPagelet(c)&&(b=g(c),b.remove());if(g.hasPagelet(c))if(b=g(c),b.isUnloading())b.on("afterunload",this._doArrive,this,a);else throw Error("unbeliveble");else this._doArrive(a)},_doArrive:function(a){var c,d,e,i,f,l,o,h;c=a.id||null;d=a.content?a.content:a.container_id?j(a.container_id,a.doc):null;a.html=d;d=g(c);if(e=a.hook)for(i in e){f=e[i];o=f.length;for(l=-1;++l<o;){h=f[l];try{d.on(i,x(h)?h:new Function("pagelet",h),b,d)}catch(w){throw Error("Error on add script:"+
f[l]);}}}d.arrive(a);d.on("afterload",function(a){this.emit("arrived",a)},this,c)}});return e});var F=g("BigPipe");m.BigPipe=new F})(this,window,document);
(function(m,k){function h(a,b,c,d){var e,g,h;g=b.length;e=l[a]||{};e.name=a;e.factory=c;e.deps=b;e.flag=d||r;e.waiting=g;i[a]=e;delete l[a];for(c=0;c<g;c++)h=b[c],(d=i[h])?h=d.waiting:(d=l[h]=l[h]||{},h=!0),h?(d=d.refs=d.refs||[],d.push(a)):e.waiting--;e.waiting||f(e)}function f(a){var b=a.refs,c=a.name,d;a.flag&p&&(g(c),delete i[c]);if(b)for(c=0,d=b.length;c<d;c++)(a=i[b[c]])&&a.waiting&&(--a.waiting||f(a))}function g(a){var b,c,d,e,f,h;b=i[a];if(!b)throw Error('Requiring unknown module "'+a+'"');
if(b.error)throw Error('Requiring module "'+a+'" which threw an exception');if(b.waiting)throw Error('Requiring module "'+a+'" with unresolved dependencies');if(b.hasOwnProperty("exports"))return b.exports;b.exports=a={};c=b.deps;h=c.length;f=-1;for(e=[];++f<h;)d=c[f],e.push("module"===d?b:"exports"===d?a:g(d));if(void 0!==(c=b.factory.apply(this,e)))b.exports=a=c;return a}function b(a,b){function c(){--i||d()}function d(){var c=[],i;for(i=0;i<e;i++)c.push(g(a[i]));b&&b.apply(this,c)}var e,i,f,h;
if(i=e=a.length)for(f=0;f<e;f++)h=a[f],k.loadModule(h,c);else d()}function e(a,c){x?(h("__mod_"+y++,a,c,p),b(a)):q.push([a,c])}function a(){if(!x){x=!0;var a,c,d,e;for(a=0,c=q.length;a<c;a++)d=q[a],e=d[0],d=d[1],h("__mod_"+y++,e,d,p),b(e);q=null}}function d(a,b){i[a]={exports:b,waiting:0}}function c(){k.log.apply(k,arguments)}var i={},l={},q=[],r=0,p=1,y=0,t,x=!1;document.addEventListener?t=function(){document.removeEventListener("DOMContentLoaded",t,!1);a()}:document.attachEvent&&(t=function(){"complete"===
document.readyState&&(document.detachEvent("onreadystatechange",t),a())});g.__debug__=i;g.__waiting__=l;document.addEventListener?(document.addEventListener("DOMContentLoaded",t,!1),window.addEventListener("load",a,!1)):document.attachEvent&&(document.attachEvent("onreadystatechange",t),window.attachEvent("onload",a));d("global",m);d("module",1);d("exports",1);d("require",g);d("requireAsync",b);d("requireLazy",e);m.define=h;m.require=g;m.requireAsync=b;m.requireLazy=e;m.__d=function(a,b,c){return h(a,
"global,module,exports,require,requireAsync,requireLazy".split(",").concat(b),c)};m.console||(m.console={log:c,error:c,dir:c})})(window,BigPipe);__d("common.js.config",[],function(m,k,h){function f(b){var b=b||{},e;for(e in b)b.hasOwnProperty(e)&&(g[e]=b[e]);f=function(){}}var g={};return h={__config__:g,init:f,get:function(b,e){return g.hasOwnProperty(b)?g[b]:e}}});
__d("common.js.events",[],function(m,k,h){function f(a,b){var c=a[0],e=a[1],b=a[2].concat(b);try{return c.apply(e,b)}catch(f){setTimeout(function(){throw f;},0)}}function g(a,d){var c=b[a],i,g,h;if(!c)return!0;d=e.call(arguments,1);c=c.cbs;i=c.length;g=-1;for(h=!0;++g<i;)h=!1!==f(c[g],d)&&h;return!!h}var b={},e=[].slice;return h={on:function(a,d,c){var i,g,h;if(!(i=b[a]))b[a]=i={args:null,cbs:[]};c=c||m;g=[d,c,e.call(arguments,3)];(h=i.args)?f(g,h):i.cbs.push(g)},un:function(a,d){var c=b[a],e;if(!c)return!0;
if(1==arguments.length)c.cbs=[];else{c=c.cbs;for(e=c.length;e--;)c[e]===d&&c.splice(e,1)}},emit:function(a,b){return g.apply(this,arguments)},done:function(a,d){var c,i,f;if(!(c=b[a]))b[a]=c={args:d,cbs:[]};i=c.cbs;f=i.length;d=e.call(arguments,1);c.args=d;g.apply(this,arguments);c.cbs=i.slice(f)},undo:function(a){a=b[a];if(!a)return!1;a.args=null}}});
__d("common.js.pageEvents",["common.js.events"],function(m,k,h,f){function g(a,b,c){a.addEventListener?a.addEventListener(b,c,!1):a.attachEvent?a.attachEvent("on"+b,c):a["on"+b]=c}function b(){var a={},b;b=null!=window.innerHeight?{width:window.innerWidth,height:window.innerHeight}:"CSS1Compat"==document.compatMode?{width:document.documentElement.clientWidth,height:document.documentElement.clientHeight}:{width:document.body.clientWidth,height:document.body.clientHeight};var c;c=null!=window.pageXOffset?
{scrollLeft:window.pageXOffset,scrollTop:window.pageYOffset}:"CSS1Compat"==document.compatMode?{scrollLeft:document.documentElement.scrollLeft,scrollTop:document.documentElement.scrollTop}:{scrollLeft:document.body.scrollLeft,scrollTop:document.body.scrollTop};a.height=b.height;a.width=b.width;a.scrollLeft=c.scrollLeft;a.scrollTop=c.scrollTop;return a}function e(a,d){var e;l?clearTimeout(l):(e=b(),e.originalEvent=a&&a.originalEvent,c.emit("viewport.startchange",e));c.emit("viewport.change",a);l=setTimeout(function(){l=
0;e=b();e.originalEvent=a&&a.originalEvent;c.emit("viewport.deferchange",e)},d||20)}function a(a,b){function d(){r=0;c.emit("page.endchange",a)}var b=b||0,e=+new Date+b;r||c.emit("page.startchange",a);c.emit("page.change",a);p<e&&(p=e,b?(clearTimeout(r),r=setTimeout(d,b)):d())}function d(){this.emitViewportChange=e;this.emitPageChange=a;this.getViewport=b}for(var c=f("common.js.events"),m=[[window,"scroll","window.scroll"],[window,"resize","window.resize"]],i,l,k=m.length;k--;){var q,h=m[k],f=h[0];
i=h[1];q=h[2];g(f,i,function(a){c.emit(q,{originalEvent:a})})}var r=0,p=0;c.on("window.scroll",e);c.on("window.resize",e);c.done("window.init",b());d.prototype=c;return h=new d});
__d("common.js.queue",[],function(m,k,h){function f(a,d,c){b.push([a,d,c]);if(!e){for(e=!0;a=b.length;){for(d=0;d<a;d++)c=b[d],c[0].apply(c[1],c[2]);b.splice(0,a)}e=!1}}function g(a,b,c){var e=Array.prototype.slice;g=function(a,b,c){var d=e.call(arguments,1);return e.apply(a,d)};return g.apply(this,g(arguments,0))}var b=[],e=!1;return h={call:function(a,b){return f(a,b,g(arguments,2))},apply:f}});
__d("common.js.lazy",["common.js.pageEvents","common.js.queue"],function(m,k,h,f,g,b){function e(){o==y&&(o=t,b(["common.js.jquery"],function(){o=x;e=a;l.call(e)}))}function a(){var a,b,d;for(a=0,b=q.length;a<b;a++){d=q[a];void 0===d.offsetTop&&d.valid&&(d.offsetTop=c(d.elem));var e;if(e=void 0!==d.offsetTop)d.valid?p.scrollTop+p.height+10>d.offsetTop?(l.call(d.callback,m,d.elem),e=!0):e=!1:e=!0;e&&(q.splice(a,1),a--,b--)}}function d(a){a.setAttribute("src",a.getAttribute("data-src"))}function c(a){var b=
0,c;try{for(;0>=b;){if(!a||!(c=$(a).offset()))return;b=c.top;a=a.parentNode}}catch(d){return}return b}var i=f("common.js.pageEvents"),l=f("common.js.queue"),q=[],r=0,p,y=1,t=2,x=3,o=y;i.on("viewport.change",function(){p=i.getViewport();l.call(e)});i.on("page.endchange",function(){for(var a=0,b=q.length;a<b;a++)q[a].offsetTop=void 0;l.call(e)});return h={add:function(a,b){"length"in a||(a=[a]);for(var c=0,g,f=a.length;c<f;c++)g={elem:a[c],callback:b||d,key:r,valid:!0},q.push(g);p||(p=i.getViewport());
l.call(e);return r++},remove:function(a){for(var b=q.length;b--;)q[b].key===a&&(q.valid=!1)}}});
__d("common.js.bigRender",["common.js.lazy"],function(m,k,h,f){function g(b,a){if(b){var d=b.className;0==d.length?b.className=a:d==a||d.match(RegExp("(^|\\s)"+a+"(\\s|$)"))||(b.className=d+" "+a)}}var b=f("common.js.lazy");return h={add:function(e){var a,d;try{return d=document.getElementById(e.id),g(d,"g-bigrender"),a=b.add(d,function(){e.load();e.on("display",function(){if(d){var a=d.className;0!=a.length&&("g-bigrender"==a?d.className="":a.match(/(^|\s)g-bigrender(\s|$)/)&&(d.className=a.replace(/(^|\s)g-bigrender(\s|$)/,
" ")))}})}),e.on("unload",function(){b.remove(a)}),!0}catch(c){return setTimeout(function(){throw c;},0),!1}}}});
__d("common.js.load",[],function(m,k,h){var f=document;return h={loadScript:function(g,b,e){b=f.createElement("script");f.getElementsByTagName("head");e=e||{};b.type="text/javascript";b.src=g;var g=b,b=null,a;for(a in e)b=f.createAttribute(a),b.value=e[a],g.setAttributeNode(b);f.body.appendChild(g)},loadScriptString:function(g){var b=f.createElement("script");b.type="text/javascript";try{b.appendChild(f.createTextNode(g))}catch(e){b.text=g}f.body.appendChild(b)},loadStyle:function(){},loadStyleString:function(g){var b=
f.createElement("style"),e=f.getElementsByTagName("head")[0];b.type="text/css";try{b.appendChild(f.createTextNode(g))}catch(a){b.styleSheet.cssText=g}e.appendChild(b)}}});
__d("common.js.format",[],function(){function m(k,h){var f=Array.prototype.slice.call(arguments,1),g=Object.prototype.toString;return f.length?(f=1==f.length?null!==h&&/\[object Array\]|\[object Object\]/.test(g.call(h))?h:f:f,k.replace(/#\{(.+?)\}/g,function(b,e){var a,d,c,i,h;if(!f)return"";a=e.split("|");d=f[a[0]];"[object Function]"==g.call(d)&&(d=d(a[0]));for(c=1,i=a.length;c<i;++c)h=m.filters[a[c]],"[object Function]"==g.call(h)&&(d=h(d));return"undefined"==typeof d||null===d?"":d})):k}m.filters=
{escapeJs:function(k){if(!k||"string"!=typeof k)return k;var h,f,g,b=[];for(h=0,f=k.length;h<f;++h)g=k.charCodeAt(h),255<g?b.push(k.charAt(h)):b.push("\\x"+g.toString(16));return b.join("")},escapeString:function(k){return!k||"string"!=typeof k?k:k.replace(/["'<>\\\/`]/g,function(h){return"&#"+h.charCodeAt(0)+";"})},escapeUrl:function(k){return!k||"string"!=typeof k?k:encodeURIComponent(k)},toInt:function(k){return parseInt(k,10)||0}};m.filters.js=m.filters.escapeJs;m.filters.e=m.filters.escapeString;
m.filters.u=m.filters.escapeUrl;m.filters.i=m.filters.toInt;return m});
__d("common.js.count",["common.js.config","common.js.load","common.js.config","common.js.format"],function(m,k,h,f){function g(){var e=b.get("userinfo"),a="",a=e.iscuser?a+"1":a+"0",a=e.recommendData?a+"1":a+"0";return a=e.isauser?a+"1":a+"0"}var b=f("common.js.config");return function(){var b=f("common.js.load"),a=f("common.js.config").__config__,d=f("common.js.format"),c=g(),i="http://s0.hao123img.com/res/js/track.js?"+(+new Date/36E5|0),h=window.location.search.match(/[?&]tn=([^&<>'"]+)/)?1:0,
a={pageId:a.pageId,pf_fms:a.currentProfile.fms,pf_nav:a.currentProfile.navigate,pf_bd:""+a.currentProfile.t0+a.currentProfile.t1+a.currentProfile.t2+a.currentProfile.t3,pf_mf:a.currentProfile.mf&&a.currentProfile.mf.substr(0,1),pf_tf:a.currentProfile.tf&&a.currentProfile.tf.substr(0,1),skin:a.currentProfile.skin,isSiteUser:c,ostype:a.userinfo.ostype,rp:h};b.loadScript(i,function(){},{"data-log-config":d("level:1;page:index;pageId:#{pageId};pf_fms:#{pf_fms};pf_bd:#{pf_bd};pf_mf:#{pf_mf};pf_tf:#{pf_tf};pf_nav:#{pf_nav};rp:#{rp};skin:#{skin};isSiteUser:#{isSiteUser};ostype:#{ostype}",
a)})}});
__d("common.js.log",["common.js.config"],function(m,k,h,f){function g(a,b){for(var e in b)a[e]=b[e];return a}var b=window,e=f("common.js.config").get("logConf",{level:1,page:"index"}),a="/images/track.gif";return function(d){var c={},f=d.r=+new Date,h=b["__logImg_"+f]=new Image,k=[];a=d.url||a;var c=g(c,e),c=g(c,d),m;for(m in c)"url"!=m&&k.push(encodeURIComponent(m)+"="+encodeURIComponent(c[m]));h.onload=h.onerror=function(){b["__logImg_"+f]=null;b["__logImg_"+f]=void 0};h.src=a+"?"+k.join("&");h=
k=null}});__d("common.js.hearbeat",["common.js.log"],function(m,k,h,f){var g=f("common.js.log");return function(b,e){function a(){var a={},c;for(c in b)a[c]="[object Function]"==Object.prototype.toString.call(b[c])?b[c]():b[c];g(a);d()}function d(){c++;setTimeout(a,"[object Function]"==Object.prototype.toString.call(e)?e(c):e)}var c=0;d()}});
__d("site.hearbeat",["common.js.hearbeat"],function(m,k,h,f){var g=f("common.js.hearbeat");return function(){var b;0.01>Math.random()&&(b=+new Date,g({type:"heartbeat",sessionid:b,staytime:function(){return+new Date-b}},function(b){var a;a=Math.pow(b-1,2);b=Math.pow(b,2);return 1E3*(a+(b-a)*Math.random())}))}});window.js_YbmtsEecsd&&window.js_YbmtsEecsd(!0);
